name: Deploy to Prod

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  THEME_DIR: themes/seedlet-child
  PLUGIN_DIR: plugins/grd-acf-blocks

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["8.1"]
        node-versions: ["lts/*"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node ${{matrix.node-versions}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-versions}}
          cache: "npm"
          cache-dependency-path: "${{ env.THEME_DIR }}/package-lock.json"

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Configure Composer
        id: composer-cache
        run: |
          echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install WordPress Plugins
        run: composer install --prefer-dist --no-dev

      - name: Build Theme
        run: |
          cd ${{ env.THEME_DIR }}
          composer install
          npm i --ignore-scripts --legacy-peer-deps
          npm run build

      - name: Build Plugin
        run: |
          cd ${{ env.PLUGIN_DIR }}
          composer install
          npm i --ignore-scripts --legacy-peer-deps
          npm run build

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: "-v -a -z --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: ".phpcs.xml,.htaccess,README.md,.git*,.gitattributes,.github/,.vscode/,.gitignore,advanced-cache.php,auth.json,cache/,composer.json,composer.lock,db.php,debug.log,mu-plugins/mu-plugin.php,mysql.sql,node_modules/,object-cache.php,package-lock.json,package.json,themes/twenty*,upgrade/,uploads/,wp-cache-config.php"
