name: Theme Assertions

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  theme-assertions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "themes/seedlet-child"

    strategy:
      matrix:
        php-versions: ["8.1"]
        node-versions: ["lts/*"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node ${{matrix.node-versions}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-versions}}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpcs, composer:v2

      - name: Configure Composer
        id: composer-cache
        run: |
          echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Theme Dependencies
        run: |
          composer install
          npm i --ignore-scripts --legacy-peer-deps

      - name: Lint Theme
        run: npm run lint

      - name: Test Theme Build
        run: npm run build
