name: Theme Assertions

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  theme-assertions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "themes/insta"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: phpcs, composer:v2

      - name: Setup Composer
        id: composer-cache
        run: |
          echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Theme Dependencies
        run: |
          composer install
          npm ci --ignore-scripts

      - name: Lint Theme
        run: npm run lint

      - name: Test Theme Build
        run: npm run build
